# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'improviser/qtGUI/block.ui'
#
# Created: Fri Jan 30 06:53:39 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_blockDialog(object):
    def setupUi(self, blockDialog):
        blockDialog.setObjectName("blockDialog")
        blockDialog.resize(575, 255)
        blockDialog.setModal(True)
        self.buttonBox = QtGui.QDialogButtonBox(blockDialog)
        self.buttonBox.setGeometry(QtCore.QRect(220, 210, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtGui.QGroupBox(blockDialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 551, 191))
        self.groupBox.setObjectName("groupBox")
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(300, 70, 111, 17))
        self.label_5.setObjectName("label_5")
        self.bpm = QtGui.QSpinBox(self.groupBox)
        self.bpm.setGeometry(QtCore.QRect(150, 70, 121, 23))
        self.bpm.setMinimum(0)
        self.bpm.setMaximum(1000)
        self.bpm.setProperty("value", QtCore.QVariant(0))
        self.bpm.setObjectName("bpm")
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(30, 70, 111, 17))
        self.label_6.setObjectName("label_6")
        self.wildness = QtGui.QDoubleSpinBox(self.groupBox)
        self.wildness.setGeometry(QtCore.QRect(150, 110, 121, 23))
        self.wildness.setDecimals(5)
        self.wildness.setMaximum(100.0)
        self.wildness.setSingleStep(0.025)
        self.wildness.setProperty("value", QtCore.QVariant(0.0))
        self.wildness.setObjectName("wildness")
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(30, 110, 111, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(300, 110, 101, 17))
        self.label_8.setObjectName("label_8")
        self.resolution = QtGui.QComboBox(self.groupBox)
        self.resolution.setGeometry(QtCore.QRect(420, 70, 111, 22))
        self.resolution.setObjectName("resolution")
        self.key = QtGui.QComboBox(self.groupBox)
        self.key.setGeometry(QtCore.QRect(420, 110, 111, 22))
        self.key.setObjectName("key")
        self.duration = QtGui.QSpinBox(self.groupBox)
        self.duration.setGeometry(QtCore.QRect(420, 150, 111, 23))
        self.duration.setMinimum(0)
        self.duration.setMaximum(1000)
        self.duration.setProperty("value", QtCore.QVariant(0))
        self.duration.setObjectName("duration")
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(300, 150, 101, 17))
        self.label_9.setObjectName("label_9")
        self.blockcombo = QtGui.QComboBox(self.groupBox)
        self.blockcombo.setGeometry(QtCore.QRect(150, 30, 381, 22))
        self.blockcombo.setObjectName("blockcombo")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 30, 56, 17))
        self.label.setObjectName("label")
        self.swing = QtGui.QComboBox(self.groupBox)
        self.swing.setGeometry(QtCore.QRect(150, 150, 121, 22))
        self.swing.setObjectName("swing")
        self.swing.addItem(QtCore.QString())
        self.swing.addItem(QtCore.QString())
        self.swing.addItem(QtCore.QString())
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 150, 56, 17))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(blockDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), blockDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), blockDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(blockDialog)
        blockDialog.setTabOrder(self.blockcombo, self.bpm)
        blockDialog.setTabOrder(self.bpm, self.resolution)
        blockDialog.setTabOrder(self.resolution, self.wildness)
        blockDialog.setTabOrder(self.wildness, self.key)
        blockDialog.setTabOrder(self.key, self.swing)
        blockDialog.setTabOrder(self.swing, self.duration)
        blockDialog.setTabOrder(self.duration, self.buttonBox)

    def retranslateUi(self, blockDialog):
        blockDialog.setWindowTitle(QtGui.QApplication.translate("blockDialog", "Edit Block", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("blockDialog", "Default settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("blockDialog", "Default resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.bpm.setToolTip(QtGui.QApplication.translate("blockDialog", "A BPM of 0 means that this block will use the movement\'s BPM", None, QtGui.QApplication.UnicodeUTF8))
        self.bpm.setStatusTip(QtGui.QApplication.translate("blockDialog", "A BPM of 0 means that this block will use the movement\'s BPM", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("blockDialog", "Default BPM", None, QtGui.QApplication.UnicodeUTF8))
        self.wildness.setToolTip(QtGui.QApplication.translate("blockDialog", "If the wildness is 0, this block will use the movement\'s wildness", None, QtGui.QApplication.UnicodeUTF8))
        self.wildness.setStatusTip(QtGui.QApplication.translate("blockDialog", "If the wildness is 0, this block will use the movement\'s wildness", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("blockDialog", "Default wildness", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("blockDialog", "Default key", None, QtGui.QApplication.UnicodeUTF8))
        self.duration.setToolTip(QtGui.QApplication.translate("blockDialog", "How many times a block should be played. Set to 0 to use the movement\'s duration", None, QtGui.QApplication.UnicodeUTF8))
        self.duration.setStatusTip(QtGui.QApplication.translate("blockDialog", "How many times a block should be played. Set to 0 to use the movement\'s duration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("blockDialog", "Block duration", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("blockDialog", "Block", None, QtGui.QApplication.UnicodeUTF8))
        self.swing.setItemText(0, QtGui.QApplication.translate("blockDialog", "From movement", None, QtGui.QApplication.UnicodeUTF8))
        self.swing.setItemText(1, QtGui.QApplication.translate("blockDialog", "No swing", None, QtGui.QApplication.UnicodeUTF8))
        self.swing.setItemText(2, QtGui.QApplication.translate("blockDialog", "Swing", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("blockDialog", "Swing", None, QtGui.QApplication.UnicodeUTF8))

