# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'improviser/qtGUI/instrument.ui'
#
# Created: Fri Jan 23 19:06:51 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_instrumentDialog(object):
    def setupUi(self, instrumentDialog):
        instrumentDialog.setObjectName("instrumentDialog")
        instrumentDialog.resize(415, 275)
        instrumentDialog.setModal(True)
        self.buttonBox = QtGui.QDialogButtonBox(instrumentDialog)
        self.buttonBox.setGeometry(QtCore.QRect(50, 220, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.step = QtGui.QSpinBox(instrumentDialog)
        self.step.setGeometry(QtCore.QRect(320, 80, 71, 23))
        self.step.setMaximum(10000)
        self.step.setObjectName("step")
        self.stepstart = QtGui.QSpinBox(instrumentDialog)
        self.stepstart.setGeometry(QtCore.QRect(140, 110, 71, 23))
        self.stepstart.setMaximum(10000)
        self.stepstart.setObjectName("stepstart")
        self.stepend = QtGui.QSpinBox(instrumentDialog)
        self.stepend.setGeometry(QtCore.QRect(320, 110, 71, 23))
        self.stepend.setMinimum(-1)
        self.stepend.setMaximum(10000)
        self.stepend.setObjectName("stepend")
        self.label = QtGui.QLabel(instrumentDialog)
        self.label.setGeometry(QtCore.QRect(20, 110, 71, 17))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(instrumentDialog)
        self.label_2.setGeometry(QtCore.QRect(230, 110, 71, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(instrumentDialog)
        self.label_3.setGeometry(QtCore.QRect(230, 80, 56, 17))
        self.label_3.setObjectName("label_3")
        self.midi = QtGui.QComboBox(instrumentDialog)
        self.midi.setGeometry(QtCore.QRect(140, 50, 251, 22))
        self.midi.setObjectName("midi")
        self.label_4 = QtGui.QLabel(instrumentDialog)
        self.label_4.setGeometry(QtCore.QRect(20, 50, 111, 17))
        self.label_4.setObjectName("label_4")
        self.chance = QtGui.QDoubleSpinBox(instrumentDialog)
        self.chance.setGeometry(QtCore.QRect(140, 140, 71, 23))
        self.chance.setSingleStep(0.025)
        self.chance.setProperty("value", QtCore.QVariant(1.0))
        self.chance.setObjectName("chance")
        self.label_5 = QtGui.QLabel(instrumentDialog)
        self.label_5.setGeometry(QtCore.QRect(20, 140, 56, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(instrumentDialog)
        self.label_6.setGeometry(QtCore.QRect(20, 80, 56, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(instrumentDialog)
        self.label_7.setGeometry(QtCore.QRect(20, 170, 111, 17))
        self.label_7.setObjectName("label_7")
        self.noteduration = QtGui.QSpinBox(instrumentDialog)
        self.noteduration.setGeometry(QtCore.QRect(140, 170, 71, 23))
        self.noteduration.setMinimum(1)
        self.noteduration.setObjectName("noteduration")
        self.letring = QtGui.QCheckBox(instrumentDialog)
        self.letring.setGeometry(QtCore.QRect(20, 200, 83, 22))
        self.letring.setObjectName("letring")
        self.label_8 = QtGui.QLabel(instrumentDialog)
        self.label_8.setGeometry(QtCore.QRect(230, 140, 81, 17))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtGui.QLabel(instrumentDialog)
        self.label_9.setGeometry(QtCore.QRect(230, 170, 81, 17))
        self.label_9.setObjectName("label_9")
        self.maxvelocity = QtGui.QSpinBox(instrumentDialog)
        self.maxvelocity.setGeometry(QtCore.QRect(320, 140, 71, 23))
        self.maxvelocity.setMaximum(128)
        self.maxvelocity.setObjectName("maxvelocity")
        self.minvelocity = QtGui.QSpinBox(instrumentDialog)
        self.minvelocity.setGeometry(QtCore.QRect(320, 170, 71, 23))
        self.minvelocity.setMaximum(128)
        self.minvelocity.setObjectName("minvelocity")
        self.label_10 = QtGui.QLabel(instrumentDialog)
        self.label_10.setGeometry(QtCore.QRect(20, 20, 101, 17))
        self.label_10.setObjectName("label_10")
        self.algorithm = QtGui.QComboBox(instrumentDialog)
        self.algorithm.setGeometry(QtCore.QRect(140, 20, 251, 22))
        self.algorithm.setObjectName("algorithm")
        self.channel = QtGui.QSpinBox(instrumentDialog)
        self.channel.setGeometry(QtCore.QRect(140, 80, 71, 23))
        self.channel.setMinimum(1)
        self.channel.setMaximum(16)
        self.channel.setObjectName("channel")

        self.retranslateUi(instrumentDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), instrumentDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), instrumentDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(instrumentDialog)
        instrumentDialog.setTabOrder(self.algorithm, self.midi)
        instrumentDialog.setTabOrder(self.midi, self.channel)
        instrumentDialog.setTabOrder(self.channel, self.step)
        instrumentDialog.setTabOrder(self.step, self.stepstart)
        instrumentDialog.setTabOrder(self.stepstart, self.stepend)
        instrumentDialog.setTabOrder(self.stepend, self.chance)
        instrumentDialog.setTabOrder(self.chance, self.maxvelocity)
        instrumentDialog.setTabOrder(self.maxvelocity, self.noteduration)
        instrumentDialog.setTabOrder(self.noteduration, self.minvelocity)
        instrumentDialog.setTabOrder(self.minvelocity, self.letring)
        instrumentDialog.setTabOrder(self.letring, self.buttonBox)

    def retranslateUi(self, instrumentDialog):
        instrumentDialog.setWindowTitle(QtGui.QApplication.translate("instrumentDialog", "Edit Instrument", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("instrumentDialog", "Step start", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("instrumentDialog", "Step end", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("instrumentDialog", "Step", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("instrumentDialog", "MIDI Instrument", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("instrumentDialog", "Chance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("instrumentDialog", "Channel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("instrumentDialog", "Max note duration", None, QtGui.QApplication.UnicodeUTF8))
        self.letring.setText(QtGui.QApplication.translate("instrumentDialog", "Let ring", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("instrumentDialog", "Max velocity", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("instrumentDialog", "Min velocity", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("instrumentDialog", "Algorithm", None, QtGui.QApplication.UnicodeUTF8))

