# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'instrument.ui'
#
# Created: Fri Jan 30 13:47:24 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_instrumentDialog(object):
    def setupUi(self, instrumentDialog):
        instrumentDialog.setObjectName("instrumentDialog")
        instrumentDialog.resize(608, 303)
        instrumentDialog.setModal(True)
        self.verticalLayout = QtGui.QVBoxLayout(instrumentDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Tabs = QtGui.QTabWidget(instrumentDialog)
        self.Tabs.setObjectName("Tabs")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_10 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(150, 0))
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.algorithm = QtGui.QComboBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.algorithm.sizePolicy().hasHeightForWidth())
        self.algorithm.setSizePolicy(sizePolicy)
        self.algorithm.setMinimumSize(QtCore.QSize(150, 0))
        self.algorithm.setObjectName("algorithm")
        self.gridLayout_2.addWidget(self.algorithm, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(150, 0))
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.midi = QtGui.QComboBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.midi.sizePolicy().hasHeightForWidth())
        self.midi.setSizePolicy(sizePolicy)
        self.midi.setMinimumSize(QtCore.QSize(150, 0))
        self.midi.setObjectName("midi")
        self.gridLayout_2.addWidget(self.midi, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(150, 0))
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.channel = QtGui.QSpinBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channel.sizePolicy().hasHeightForWidth())
        self.channel.setSizePolicy(sizePolicy)
        self.channel.setMinimumSize(QtCore.QSize(75, 0))
        self.channel.setMinimum(1)
        self.channel.setMaximum(16)
        self.channel.setObjectName("channel")
        self.gridLayout_2.addWidget(self.channel, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(150, 0))
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.chance = QtGui.QDoubleSpinBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chance.sizePolicy().hasHeightForWidth())
        self.chance.setSizePolicy(sizePolicy)
        self.chance.setMinimumSize(QtCore.QSize(75, 0))
        self.chance.setSingleStep(0.025)
        self.chance.setProperty("value", QtCore.QVariant(1.0))
        self.chance.setObjectName("chance")
        self.gridLayout_2.addWidget(self.chance, 3, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.Tabs.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(150, 0))
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.step = QtGui.QSpinBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step.sizePolicy().hasHeightForWidth())
        self.step.setSizePolicy(sizePolicy)
        self.step.setMinimumSize(QtCore.QSize(75, 0))
        self.step.setMaximum(10000)
        self.step.setObjectName("step")
        self.gridLayout_3.addWidget(self.step, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(150, 0))
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.stepstart = QtGui.QSpinBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepstart.sizePolicy().hasHeightForWidth())
        self.stepstart.setSizePolicy(sizePolicy)
        self.stepstart.setMinimumSize(QtCore.QSize(75, 0))
        self.stepstart.setMaximum(10000)
        self.stepstart.setObjectName("stepstart")
        self.gridLayout_3.addWidget(self.stepstart, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(150, 0))
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.stepend = QtGui.QSpinBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepend.sizePolicy().hasHeightForWidth())
        self.stepend.setSizePolicy(sizePolicy)
        self.stepend.setMinimumSize(QtCore.QSize(75, 0))
        self.stepend.setMinimum(-1)
        self.stepend.setMaximum(10000)
        self.stepend.setProperty("value", QtCore.QVariant(-1))
        self.stepend.setObjectName("stepend")
        self.gridLayout_3.addWidget(self.stepend, 2, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 3, 0, 1, 1)
        self.end = QtGui.QSpinBox(self.tab_2)
        self.end.setMinimum(-1)
        self.end.setMaximum(100000)
        self.end.setProperty("value", QtCore.QVariant(-1))
        self.end.setObjectName("end")
        self.gridLayout_3.addWidget(self.end, 3, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.Tabs.addTab(self.tab_2, "")
        self.Notes = QtGui.QWidget()
        self.Notes.setObjectName("Notes")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.Notes)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_9 = QtGui.QLabel(self.Notes)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(150, 0))
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 2, 0, 1, 1)
        self.minvelocity = QtGui.QSpinBox(self.Notes)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minvelocity.sizePolicy().hasHeightForWidth())
        self.minvelocity.setSizePolicy(sizePolicy)
        self.minvelocity.setMinimumSize(QtCore.QSize(75, 0))
        self.minvelocity.setMaximum(128)
        self.minvelocity.setObjectName("minvelocity")
        self.gridLayout_4.addWidget(self.minvelocity, 2, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.Notes)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.Notes)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 1, 0, 1, 1)
        self.minnote = QtGui.QComboBox(self.Notes)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minnote.sizePolicy().hasHeightForWidth())
        self.minnote.setSizePolicy(sizePolicy)
        self.minnote.setMinimumSize(QtCore.QSize(75, 0))
        self.minnote.setObjectName("minnote")
        self.gridLayout_4.addWidget(self.minnote, 0, 1, 1, 1)
        self.maxnote = QtGui.QComboBox(self.Notes)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxnote.sizePolicy().hasHeightForWidth())
        self.maxnote.setSizePolicy(sizePolicy)
        self.maxnote.setMinimumSize(QtCore.QSize(75, 0))
        self.maxnote.setObjectName("maxnote")
        self.gridLayout_4.addWidget(self.maxnote, 1, 1, 1, 1)
        self.maxvelocity = QtGui.QSpinBox(self.Notes)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxvelocity.sizePolicy().hasHeightForWidth())
        self.maxvelocity.setSizePolicy(sizePolicy)
        self.maxvelocity.setMinimumSize(QtCore.QSize(75, 0))
        self.maxvelocity.setMaximum(128)
        self.maxvelocity.setObjectName("maxvelocity")
        self.gridLayout_4.addWidget(self.maxvelocity, 3, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.Notes)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(150, 0))
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 3, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_4)
        self.Tabs.addTab(self.Notes, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.minnoteduration = QtGui.QSpinBox(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minnoteduration.sizePolicy().hasHeightForWidth())
        self.minnoteduration.setSizePolicy(sizePolicy)
        self.minnoteduration.setMinimumSize(QtCore.QSize(75, 0))
        self.minnoteduration.setMinimum(1)
        self.minnoteduration.setMaximum(128)
        self.minnoteduration.setObjectName("minnoteduration")
        self.gridLayout.addWidget(self.minnoteduration, 0, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.tab_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(150, 0))
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.noteduration = QtGui.QSpinBox(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noteduration.sizePolicy().hasHeightForWidth())
        self.noteduration.setSizePolicy(sizePolicy)
        self.noteduration.setMinimumSize(QtCore.QSize(75, 0))
        self.noteduration.setMinimum(1)
        self.noteduration.setMaximum(128)
        self.noteduration.setObjectName("noteduration")
        self.gridLayout.addWidget(self.noteduration, 1, 1, 1, 1)
        self.maxnotes = QtGui.QSpinBox(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxnotes.sizePolicy().hasHeightForWidth())
        self.maxnotes.setSizePolicy(sizePolicy)
        self.maxnotes.setMinimumSize(QtCore.QSize(75, 0))
        self.maxnotes.setMinimum(-1)
        self.maxnotes.setMaximum(128)
        self.maxnotes.setProperty("value", QtCore.QVariant(-1))
        self.maxnotes.setObjectName("maxnotes")
        self.gridLayout.addWidget(self.maxnotes, 2, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.Tabs.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.Tabs)
        self.buttonBox = QtGui.QDialogButtonBox(instrumentDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setMinimumSize(QtCore.QSize(0, 0))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(instrumentDialog)
        self.Tabs.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), instrumentDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), instrumentDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(instrumentDialog)

    def retranslateUi(self, instrumentDialog):
        instrumentDialog.setWindowTitle(QtGui.QApplication.translate("instrumentDialog", "Edit Instrument", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("instrumentDialog", "Algorithm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("instrumentDialog", "MIDI Instrument", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("instrumentDialog", "Channel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("instrumentDialog", "Chance", None, QtGui.QApplication.UnicodeUTF8))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab), QtGui.QApplication.translate("instrumentDialog", "Global", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("instrumentDialog", "Step", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("instrumentDialog", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("instrumentDialog", "Step end", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("instrumentDialog", "End", None, QtGui.QApplication.UnicodeUTF8))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_2), QtGui.QApplication.translate("instrumentDialog", "Step", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("instrumentDialog", "Min velocity", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("instrumentDialog", "Min note", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("instrumentDialog", "Max note", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("instrumentDialog", "Max velocity", None, QtGui.QApplication.UnicodeUTF8))
        self.Tabs.setTabText(self.Tabs.indexOf(self.Notes), QtGui.QApplication.translate("instrumentDialog", "Notes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("instrumentDialog", "Min note duration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("instrumentDialog", "Max note duration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("instrumentDialog", "Max simultaneous notes", None, QtGui.QApplication.UnicodeUTF8))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_3), QtGui.QApplication.translate("instrumentDialog", "Duration", None, QtGui.QApplication.UnicodeUTF8))

